import 'voice_service.dart';

/// Holds the current locale and all translated strings.
/// Call [init] once in main() before runApp.
class AppLanguage {
  static String current = 'en';

  static Future<void> init() async => VoiceService.init();

  static const Map<String, Map<String, String>> _d = {
    'en': {
      'title': 'EyeComm',
      'back': 'Back',
      'more': 'More',
      'confirmed': 'Done ✅',
      'change_lang': 'Language',
      'basic': 'Basic Needs',
      'health': 'Health & Emergency',
      'smart': 'Smart Home',
      'social': 'Social & Caregiver',
      'keyboard': 'Keyboard',
      'food': 'Food',
      'drink': 'Drink',
      'toilet': 'I need the bathroom',
      'hotcold': 'Temperature',
      'bread': 'Bread',
      'eggs': 'Eggs',
      'cheese': 'Cheese',
      'yogurt': 'Yogurt',
      'chicken': 'Chicken',
      'meat': 'Meat',
      'fish': 'Fish',
      'rice': 'Rice',
      'pasta': 'Pasta',
      'potato': 'Potato',
      'vegetables': 'Vegetables',
      'fruit': 'Fruit',
      'water': 'Water',
      'milk': 'Milk',
      'juice': 'Juice',
      'coffee': 'Coffee',
      'tea': 'Tea',
      'hot': 'I feel hot',
      'cold': 'I feel cold',
      'fever': 'I have a fever',
      'ice_pack': 'Ice pack please',
      'heating_pad': 'Heating pad please',
      'medication_btn': 'Medication Alarm',
      'pain': 'Pain',
      'emergency': 'Emergency',
      'symptoms': 'Symptoms',
      'set_alarm': 'Set Alarm',
      'alarm_set': 'Alarm Set!',
      'medication_time': 'Time for your medication',
      'hour_up': 'Hour +1',
      'min_up': 'Min +5',
      'min_down': 'Min -5',
      'confirm': 'Confirm',
      'head': 'Head pain',
      'chest': 'Chest pain',
      'stomach': 'Stomach pain',
      'tooth': 'Tooth pain',
      'call911': 'Call 911 - Emergency!',
      'call_doctor': 'Call Doctor',
      'go_hospital': 'Take me to Hospital',
      'need_medicine': 'I need medicine',
      'breathing': 'Difficulty breathing',
      'nausea': 'Nausea',
      'dizzy': 'Dizzy',
      'vomiting': 'Vomiting',
      'lights': 'Turn on Lights',
      'tv': 'Turn on TV',
      'ac': 'AC Control',
      'door': 'Open Door',
      'ac_hot': 'Heater',
      'ac_cold': 'Air Conditioner',
      'temp_adjust': 'Adjust Temperature',
      'fan': 'Turn on Fan',
      'feelings': 'Feelings',
      'phrases': 'Quick Phrases',
      'greetings': 'Greetings',
      'caregiver': 'Call Caregiver',
      'happy': 'I am happy',
      'sad': 'I am sad',
      'love': 'I love you',
      'frustrated': 'I am frustrated',
      'yes': 'Yes',
      'no': 'No',
      'please': 'Please',
      'thank_you': 'Thank you',
      'help': 'Help me!',
      'hello': 'Hello, how are you?',
      'excuse_me': 'Excuse me',
      'caregiver_title': 'Caregiver Numbers',
      'add_number': 'Add Number',
      'call_now': 'Calling...',
      'scroll_up': 'Scroll Up',
      'scroll_down': 'Scroll Down',
      'select_call': 'Close eye to call',
      'no_numbers': 'No numbers saved',
      'number_added': 'Number saved',
      'number_deleted': 'Number deleted',
      'digit_up': 'Digit +1',
      'digit_down': 'Digit -1',
      'add_digit': 'Add digit',
      'save_num': 'Save number',
      'del_digit': 'Delete',
      'enter_num': 'Enter number',
      'kb_space': 'Space',
      'kb_delete': 'Delete',
      'kb_speak': 'Speak 🔊',
      'kb_clear': 'Clear All',
      'kb_select_group': 'Select letter group',
      'kb_select_letter': 'Choose letter',
      'are_you_ok': 'Are you okay? Close your eye if you are fine.',
      'no_movement_warn': 'Warning: no eye movement detected. Close your eye to confirm.',
      'emergency_alert': 'Alert! Calling caregiver in 5 seconds.',
      'calling_caregiver': 'Emergency! Calling caregiver now.',
      'smart_alarm': 'Smart Alarm',
      'alarm_label': 'Alarm Time',
    },
    'ar': {
      'title': 'آي كوم',
      'back': 'رجوع',
      'more': 'المزيد',
      'confirmed': 'تم ✅',
      'change_lang': 'اللغة',
      'basic': 'الاحتياجات الأساسية',
      'health': 'الصحة والطوارئ',
      'smart': 'المنزل الذكي',
      'social': 'التواصل والمرافق',
      'keyboard': 'الكيبورد',
      'food': 'أكل',
      'drink': 'شرب',
      'toilet': 'عايز أروح الحمام',
      'hotcold': 'الحرارة',
      'bread': 'خبز',
      'eggs': 'بيض',
      'cheese': 'جبن',
      'yogurt': 'زبادي',
      'chicken': 'دجاج',
      'meat': 'لحم',
      'fish': 'سمك',
      'rice': 'رز',
      'pasta': 'مكرونة',
      'potato': 'بطاطس',
      'vegetables': 'خضار',
      'fruit': 'فاكهة',
      'water': 'ماء',
      'milk': 'حليب',
      'juice': 'عصير',
      'coffee': 'قهوة',
      'tea': 'شاي',
      'hot': 'الجو حار',
      'cold': 'الجو بارد',
      'fever': 'عندي حمى',
      'ice_pack': 'عايز كمادة باردة',
      'heating_pad': 'عايز كمادة ساخنة',
      'medication_btn': 'منبه الدواء',
      'pain': 'ألم',
      'emergency': 'طوارئ',
      'symptoms': 'أعراض',
      'set_alarm': 'ضبط المنبه',
      'alarm_set': 'تم ضبط المنبه!',
      'medication_time': 'حان موعد الدواء',
      'hour_up': 'ساعة +1',
      'min_up': 'دقيقة +5',
      'min_down': 'دقيقة -5',
      'confirm': 'تأكيد',
      'head': 'رأسي يؤلمني',
      'chest': 'صدري يؤلمني',
      'stomach': 'معدتي تؤلمني',
      'tooth': 'ضرسي يؤلمني',
      'call911': 'اتصل بالطوارئ!',
      'call_doctor': 'اتصل بالدكتور',
      'go_hospital': 'خدني للمستشفى',
      'need_medicine': 'عايز دوا',
      'breathing': 'صعوبة في التنفس',
      'nausea': 'عندي غثيان',
      'dizzy': 'عندي دوار',
      'vomiting': 'عندي قيء',
      'lights': 'شغل النور',
      'tv': 'شغل التلفاز',
      'ac': 'التحكم في التكييف',
      'door': 'افتح الباب',
      'ac_hot': 'الدفاية',
      'ac_cold': 'التكييف',
      'temp_adjust': 'عدل درجة الحرارة',
      'fan': 'شغل المروحة',
      'feelings': 'المشاعر',
      'phrases': 'عبارات سريعة',
      'greetings': 'التحيات',
      'caregiver': 'نادي المرافق',
      'happy': 'أنا سعيد',
      'sad': 'أنا حزين',
      'love': 'أنا بحبك',
      'frustrated': 'أنا محبط',
      'yes': 'نعم',
      'no': 'لا',
      'please': 'من فضلك',
      'thank_you': 'شكراً',
      'help': 'ساعدني!',
      'hello': 'مرحباً، كيف حالك؟',
      'excuse_me': 'عذراً',
      'caregiver_title': 'أرقام المرافقين',
      'add_number': 'إضافة رقم',
      'call_now': 'جاري الاتصال...',
      'scroll_up': 'للأعلى',
      'scroll_down': 'للأسفل',
      'select_call': 'أغمض عينك للاتصال',
      'no_numbers': 'لا توجد أرقام محفوظة',
      'number_added': 'تم حفظ الرقم',
      'number_deleted': 'تم حذف الرقم',
      'digit_up': 'رقم +1',
      'digit_down': 'رقم -1',
      'add_digit': 'أضف الرقم',
      'save_num': 'حفظ',
      'del_digit': 'مسح',
      'enter_num': 'أدخل الرقم',
      'kb_space': 'مسافة',
      'kb_delete': 'مسح حرف',
      'kb_speak': 'نطق 🔊',
      'kb_clear': 'مسح الكل',
      'kb_select_group': 'اختر مجموعة الحروف',
      'kb_select_letter': 'اختر الحرف',
      'are_you_ok': 'هل أنت بخير؟ أغمض عينك إذا كنت بخير.',
      'no_movement_warn': 'تنبيه، لم نر حركة لعينك. أغمض عينك للتأكيد.',
      'emergency_alert': 'إنذار! سيتم الاتصال بالمرافق خلال 5 ثواني.',
      'calling_caregiver': 'تنبيه طوارئ! جاري الاتصال بالمرافق الآن.',
      'smart_alarm': 'منبه ذكي',
      'alarm_label': 'وقت المنبه',
    },
  };

  static String t(String k) => _d[current]?[k] ?? k;
}
